package br.com.jaemilton.quartz_cron_generator.enums;

public enum CronExpressionType {
	EVERY_N_SECONDS,
    EVERY_N_MINUTES,
    EVERY_N_HOURS,
    EVERY_DAY_AT,
    EVERY_N_DAYS_AT,
    EVERY_WEEK_DAY,
    EVERY_SPECIFIC_WEEK_DAY_AT,
    EVERY_SPECIFIC_DAY_EVERY_N_MONTH_AT,
    EVERY_SPECIFIC_SEQ_WEEK_DAY_EVERY_N_MONTH_AT,
    EVERY_SPECIFIC_DAY_OF_MONTH_AT,
    EVERY_SPECIFIC_SEQ_WEEKDAY_OF_MONTH_AT,
    EVERY_SPECIFIC_DAY_OF_SPECIFIC_MONTHS_AT,
    SPECIFIC_DATE_AT;
}
